name: "Sync GHAS Findings to Jira"

on:
  schedule:
    - cron: '*/10 * * * *'    # trigger synchronization every 10 minutes

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Sync alerts to Jira issues
        uses: github/ghas-jira-integration@v1
        with:
          jira_labels: 'security,ghas'
          jira_url: '${{ secrets.JIRA_URL }}' # Global
          jira_user: '${{ secrets.JIRA_SECENG_USER }}' # Global
          jira_token: '${{ secrets.JIRA_SECENG_TOKEN }}' # Global
          jira_project: '${{ secrets.JIRA_PROJECT }}'
          github_token: '${{ secrets.GH_SECENG_PAT }}'
          sync_direction: 'gh2jira'